import type { Action, Character, CharacterId } from '../data';
import { ABILITY_LEVELS, resourceFor } from '../progression';
import type { IconName } from '../components/Icon';

export type AbilityKind = 'primary' | 'signature' | 'nova' | 'ward' | 'volley' | 'heal' | 'zone' | 'blink' | 'meteor' | 'execute' | 'ascend' | 'chains' | 'torrent' | 'eclipse' | 'oblivion' | 'ritual';
export interface HeroAbility { id: string; name: string; description: string; action: Action; level: number; cooldown: number; cost: number; kind: AbilityKind; icon: IconName; power: number; duration: number; radius: number }
type Extra = [name: string, kind: AbilityKind, description: string, power?: number];

const extras: Record<CharacterId, [Extra, Extra, Extra, Extra]> = {
  knight: [ ['Iron Resolve', 'ward', 'Brace behind your shield. Ignore damage and reflect a shockwave.'], ['Whirlwind', 'nova', 'Spin your broadsword through every enemy around you.', 3], ['Oathbound Charge', 'blink', 'Lunge behind your target and empower your next strike.'], ['Last Bastion', 'ascend', 'Become an unbreakable juggernaut. Triple damage and invulnerability for 8 seconds.', 4] ],
  rogue: [ ['Smoke Veil', 'ward', 'Disappear into smoke. Briefly ignore incoming damage.'], ['Fan of Knives', 'volley', 'Throw seven piercing daggers in a lethal spread.', 1.8], ['Nightfall', 'chains', 'Shadow chains freeze nearby enemies before a finishing cut.', 3], ['Thousand Cuts', 'execute', 'Blinking blades strike every visible enemy with a devastating execution.', 8] ],
  mage: [ ['Cinder Ward', 'ward', 'Wrap yourself in a brief shield of fire.'], ['Inferno Volley', 'volley', 'Seven piercing firebolts scorch a wide arc.', 1.8], ['Meteor', 'meteor', 'Mark your target, then bring a burning meteor crashing down.', 5], ['Phoenix Ascension', 'ascend', 'Become living flame. Triple damage, invulnerability, and a burning shockwave.', 5] ],
  paladin: [ ['Sacred Aegis', 'ward', 'Holy armor briefly makes you immune to damage.'], ['Lay on Hands', 'heal', 'Restore 35% health and refill movement stamina.'], ['Judgment', 'meteor', 'A pillar of sunlight smites a marked area.', 5], ['Avatar of Dawn', 'ascend', 'A radiant transformation grants triple damage and invulnerability.', 4] ],
  frost: [ ['Glacial Shell', 'ward', 'A glacial barrier stops incoming damage.'], ['Winter Lances', 'volley', 'Launch seven piercing ice lances that chill their victims.', 2], ['Whiteout', 'chains', 'Freeze the whole chamber for 4 seconds.', 3], ['Absolute Zero', 'execute', 'Shatter all visible foes with a room-wide burst of frost.', 8] ],
  ranger: [ ['Windwalk', 'blink', 'Reposition behind your target and empower your next arrow.'], ['Rejuvenation', 'heal', 'Restore 35% health with a wild healing draught.'], ['Briar Snare', 'zone', 'A 6-second tangle drags enemies inward and damages them.', 1], ['Rain of Thorns', 'torrent', 'Release three consecutive radial storms of piercing arrows.', 2] ],
  berserker: [ ['War Cry', 'chains', 'Stun every nearby foe with a crushing roar.', 2], ['Blood Feast', 'heal', 'Restore 35% health and fill your movement stamina.'], ['Ravager Spin', 'nova', 'Both axes carve a wide circle through enemy ranks.', 4], ['Worldbreaker', 'ascend', 'Eight seconds of triple damage, invulnerability, and a devastating eruption.', 5] ],
  storm: [ ['Static Shield', 'ward', 'An electric barrier briefly blocks all damage.'], ['Arc Barrage', 'volley', 'Seven lightning bolts chain through clustered enemies.', 1.8], ['Thunderclap', 'chains', 'Stun the chamber in a rolling thunder shock.', 4], ['Eye of the Storm', 'torrent', 'Three expanding rings of lightning sweep the battlefield.', 2.4] ],
  plague: [ ['Antidote', 'heal', 'Recover 35% health and purge movement-impairing venom.'], ['Septic Volley', 'volley', 'Seven poisonous vials spread a lingering plague.', 1.6], ['Black Bloom', 'zone', 'A growing toxic field damages and slows enemies for 6 seconds.', 1.4], ['The Final Cure', 'execute', 'Detonate an alchemical plague across every visible enemy.', 9] ],
  reaper: [ ['Bloodmist', 'blink', 'Dissolve into mist and emerge behind your target.'], ['Sanguine Guard', 'ward', 'Crimson mist briefly shields you from every attack.'], ['Soul Vortex', 'zone', 'Pull souls into a scythe-shaped vortex for 6 seconds.', 1.3], ['Red Harvest', 'execute', 'Execute every visible enemy, feeding your vampiric lifesteal.', 9] ],
  warden: [ ['Granite Bulwark', 'ward', 'Become immovable stone, immune to incoming attacks.'], ['Faultline', 'nova', 'A fissure throws enemies back and shatters barricades.', 4], ['Living Mountain', 'heal', 'Rebuild your body, restoring 35% health.'], ['Titan Awakening', 'ascend', 'Awaken as a titan with triple damage and 8 seconds of invulnerability.', 5] ],
  monk: [ ['Still Water', 'heal', 'Restore your balance, 35% health, and all movement stamina.'], ['Lotus Guard', 'ward', 'A perfect stance turns incoming blows aside.'], ['Dragon Palm', 'nova', 'Release a long-reaching circular shockwave.', 5], ['Nine Heavens', 'torrent', 'Three waves of golden chi crash through every surrounding enemy.', 3] ],
  oracle: [ ['Astral Shift', 'blink', 'Fold space behind your target and empower your next attack.'], ['Star Ward', 'ward', 'A constellation briefly shields you from all damage.'], ['Falling Constellation', 'meteor', 'A delayed starfall crushes the marked area.', 5], ['Cosmic Requiem', 'execute', 'Unmake all visible enemies in an astral collapse.', 9] ],
  phantom: [ ['Eclipse Dominion', 'eclipse', 'Freeze the floor, become invulnerable, and command orbiting blades for 8 seconds.'], ['Abyss Walk', 'blink', 'Step through reality behind your target. Your next attack is empowered.'], ['Soul Collapse', 'zone', 'A vast singularity devours enemies and their projectiles.', 5], ['Oblivion', 'oblivion', 'Erase every spawned enemy on this floor and restore all health.'] ],
  killison: [ ['Blood Covenant', 'ward', 'Sacrifice blood to become invulnerable for 4 seconds.'], ['Hellfire Litany', 'volley', 'Seven enormous bolts of hellfire pierce the chamber.', 3], ['Altar of Ruin', 'zone', 'Open a sacrificial altar that drags foes inward and drains their life.', 2.5], ['Demon Apotheosis', 'ascend', 'Offer 22% maximum HP. Become a demon sovereign: triple damage, invulnerability, and an infernal eruption.', 9] ],
  tidecaller: [ ['Pearl Aegis', 'ward', 'A shimmering shell blocks all incoming damage for four seconds.'], ['Seafoam Renewal', 'heal', 'Recover 35% maximum health and all movement stamina.'], ['Riptide Spears', 'volley', 'Seven piercing icy lances chill a wide arc of enemies.', 2.8], ['Ocean\'s Judgment', 'torrent', 'Three radial tidal storms wash through the battlefield.', 3.2] ],
  duneblade: [ ['Sirocco Step', 'blink', 'Blink behind your target and empower your next cut.'], ['Scimitar Storm', 'volley', 'Throw seven piercing crescent blades in a wide fan.', 2.4], ['Tombbreaker', 'nova', 'A sweeping sand shockwave drives foes back.', 5], ['Thousand Suns', 'execute', 'A golden flash cuts through every visible enemy.', 11] ],
  frostguard: [ ['Permafrost Armor', 'ward', 'Become an unbreakable ice fortress for four seconds.'], ['Winter\'s Breath', 'chains', 'Freeze the chamber and crush surrounding foes.', 3.5], ['Glacial Renewal', 'heal', 'Rebuild your armor and recover 35% maximum health.'], ['Heart of the Glacier', 'ascend', 'An icy transformation grants triple damage and eight seconds of invulnerability.', 7] ],
  seraph: [ ['Halo of Mercy', 'ward', 'A celestial halo makes you immune to damage for four seconds.'], ['Starfall Choir', 'volley', 'Seven piercing astral rays erase the ranks before you.', 3], ['Judgment of Heaven', 'meteor', 'A delayed celestial impact crushes the marked area.', 7], ['Seraph Ascendant', 'ascend', 'Return to your divine form: triple damage, immunity, and a celestial eruption.', 10] ],
  malachar: [ ['Blood of Worlds', 'ward', 'Offer blood to ignore incoming damage for four seconds.'], ['Abyssal Litany', 'volley', 'Seven colossal hellfire blades tear through everything ahead.', 3.2], ['Worldgrave', 'zone', 'A blood altar drags enemies inward and drains their life for six seconds.', 3], ['The Last Horizon', 'ascend', 'Offer 22% maximum HP. A world-ending eruption grants triple damage and eight seconds of invulnerability.', 10] ],
};

const kindIcons: Record<AbilityKind, IconName> = { primary: 'sword', signature: 'bolt', nova: 'flame', ward: 'shield', volley: 'daggers', heal: 'heart', zone: 'crown', blink: 'ghost', meteor: 'flame', execute: 'skull', ascend: 'crown', chains: 'lock', torrent: 'bolt', eclipse: 'ghost', oblivion: 'skull', ritual: 'heart' };

export const abilityActions: Action[] = ['attack', 'special', 'extra1', 'extra2', 'extra3', 'extra4'];
export function abilitiesFor(hero: Character): HeroAbility[] {
  const blood = resourceFor(hero).kind === 'blood';
  const primary: HeroAbility = { id: `${hero.id}-0`, name: hero.attack, description: hero.attackText, action: 'attack', level: 1, cooldown: hero.attackRate, cost: 0, kind: 'primary', icon: hero.style === 'shadow' ? 'ghost' : ['fire', 'ice', 'arcane', 'lightning', 'poison'].includes(hero.style) ? 'flame' : 'sword', power: 1, duration: 0, radius: 0 };
  const signature: HeroAbility = { id: `${hero.id}-1`, name: hero.special, description: hero.specialText, action: 'special', level: 3, cooldown: hero.cooldown, cost: blood ? 12 : hero.id === 'rogue' ? 25 : 30, kind: 'signature', icon: blood ? 'heart' : 'bolt', power: 1, duration: 0, radius: 0 };
  return [primary, signature, ...extras[hero.id].map(([name, kind, description, power = 2], index) => ({ id: `${hero.id}-${index + 2}`, name, kind, description, action: abilityActions[index + 2], level: ABILITY_LEVELS[index + 2], cooldown: [12, 14, 18, 30][index], cost: blood ? [10, 14, 18, 22][index] : [25, 35, 45, 65][index], icon: kindIcons[kind], power, duration: index === 3 ? 8 : kind === 'ward' ? 4 : 6, radius: hero.id === 'phantom' || blood ? 185 : 110 + index * 15 }))];
}

export const abilityCostLabel = (hero: Character, ability: HeroAbility) => ability.cost === 0 ? 'FREE' : `${ability.cost}${resourceFor(hero).kind === 'blood' ? '% HP' : ` ${resourceFor(hero).short}`}`;