import { useState, type CSSProperties } from 'react';
import { artifacts, characters, ownsHero, formatTime, type Progress } from '../data';
import { enemies, type EnemyKind } from '../game/content';
import Icon, { type IconName } from './Icon';
import RelicArt from './RelicArt';
import CreaturePortrait from './CreaturePortrait';

export default function Armory({ progress, onProgress, onBack, persistent = true, adminUnlocked = false }: { progress: Progress; onProgress: (p: Progress) => void; onBack: () => void; persistent?: boolean; adminUnlocked?: boolean }) {
  const [tab, setTab] = useState<'weapons' | 'artifacts' | 'bestiary' | 'history'>('weapons');
  const [selected, setSelected] = useState(0);
  const totalKills = progress.runs.reduce((n, r) => n + r.kills, 0);
  const deepest = progress.runs.reduce((n, r) => Math.max(n, r.floor), 0);
  const totalGold = progress.runs.reduce((n, r) => n + r.gold, 0);
  const items = tab === 'artifacts' ? artifacts.map(a => ({ ...a, available: a.unlocked(progress), subtitle: a.effect })) : characters.map(c => ({ id: c.id, name: c.weapon, type: c.weaponType, icon: (['slash', 'daggers', 'fists'].includes(c.style) ? 'sword' : 'flame') as IconName, color: c.color, description: c.attackText, effect: `${c.damage} BASE DAMAGE`, requirement: `The signature weapon of ${c.name}.`, available: ownsHero(progress, c, adminUnlocked), subtitle: c.name }));
  const item = items[selected] || items[0];

  return <main className="secondary-screen armory-screen screen-enter">
    <div className="screen-heading"><button className="back-link" onClick={onBack}><Icon name="back" size={16} /> MAIN MENU</button><div className="eyebrow">WHAT REMAINS WHEN YOU FALL</div><h1>The Armory<span>.</span></h1><p>Steel earns its name. Relics keep their secrets. Every descent leaves a mark.</p></div>
    <div className="armory-stats"><div><span className="micro-label">TOTAL DESCENTS</span><strong>{String(progress.runs.length).padStart(2, '0')}</strong></div><div><span className="micro-label">DEEPEST FLOOR</span><strong>{String(deepest).padStart(2, '0')}</strong></div><div><span className="micro-label">ENEMIES SLAIN</span><strong>{totalKills.toLocaleString()}</strong></div><div><span className="micro-label">GOLD RECOVERED</span><strong>{totalGold.toLocaleString()}</strong></div></div>
    <div className="panel-tabs" role="tablist" aria-label="Armory sections">{(['weapons', 'artifacts', 'bestiary', 'history'] as const).map(name => <button role="tab" aria-selected={tab === name} key={name} className={tab === name ? 'active' : ''} onClick={() => { setTab(name); setSelected(0); }}><Icon name={name === 'weapons' ? 'armory' : name === 'artifacts' ? 'crown' : name === 'bestiary' ? 'skull' : 'clock'} size={17} />{name === 'history' ? 'RUN HISTORY' : name.toUpperCase()}<span className="tab-count">{name === 'weapons' ? `${characters.filter(c => ownsHero(progress, c, adminUnlocked)).length}/${characters.length}` : name === 'artifacts' ? `${artifacts.filter(a => a.unlocked(progress)).length}/3` : name === 'bestiary' ? 11 : progress.runs.length}</span></button>)}</div>
    {tab === 'bestiary' ? <div className="bestiary" role="tabpanel" aria-label="Dungeon bestiary"><div className="bestiary-intro"><h2>You are not alone down there.</h2><p>Eleven creatures. Different instincts. Learn their tells and turn the dungeon against them.</p></div><div className="bestiary-list">{(Object.keys(enemies) as EnemyKind[]).filter(kind => kind !== 'boss').map(kind => <article key={kind} className="bestiary-entry"><CreaturePortrait kind={kind} /><div><h3 style={{ color: enemies[kind].color }}>{enemies[kind].name}</h3><p>{enemies[kind].behavior}</p><span>{enemies[kind].hp} BASE HP <i />{enemies[kind].damage} DAMAGE</span></div></article>)}</div></div> : tab !== 'history' ? <div className="armory-collection" role="tabpanel" aria-label={tab}>
      <div className="item-grid">{items.map((entry, i) => <button className={`armory-item ${selected === i ? 'selected' : ''} ${!entry.available ? 'locked' : ''}`} key={entry.id} style={{ '--item-color': entry.color } as CSSProperties} onClick={() => setSelected(i)} aria-pressed={selected === i}>
        <span className="item-status">{!entry.available ? <Icon name="lock" size={13} /> : progress.artifact === entry.id ? 'EQUIPPED' : 'UNLOCKED'}</span><div className="item-illustration"><RelicArt id={entry.id} /></div><span className="micro-label">{entry.type}</span><h3>{entry.name}</h3><p>{entry.available ? entry.subtitle : 'Awaiting discovery'}</p>
      </button>)}</div>
      <aside className="item-inspector" key={`${tab}-${item.id}`}><span className="eyebrow">{item.available ? 'FROM YOUR COLLECTION' : 'STILL LOST TO THE DEPTHS'}</span><h2>{item.name}</h2><p>{item.description}</p><div className="item-effect"><Icon name={item.available ? 'bolt' : 'lock'} size={17} />{item.available ? item.effect : item.requirement}</div>{tab === 'artifacts' ? <button className={item.available ? 'gold-button small' : 'outline-button small'} disabled={!item.available} onClick={() => onProgress({ ...progress, artifact: progress.artifact === item.id ? null : item.id })}><Icon name={progress.artifact === item.id ? 'check' : !item.available ? 'lock' : 'crown'} size={17} />{progress.artifact === item.id ? 'UNEQUIP ARTIFACT' : item.available ? 'EQUIP ARTIFACT' : 'LOCKED'}</button> : <div className="weapon-owner"><Icon name="shield" size={17} />{item.requirement}<small>Automatically equipped when you choose this character.</small></div>}</aside>
    </div> : <div className="run-history" role="tabpanel" aria-label="Run history">
      {progress.runs.length === 0 ? <div className="empty-history"><Icon name="skull" size={43} /><h2>No names carved. Yet.</h2><p>Your completed runs will be remembered here.<br />The dungeon is waiting for its first visitor.</p><button className="text-button" onClick={onBack}>RETURN TO THE GATE <Icon name="arrow" size={16} /></button></div> : <div className="history-table-wrap"><table className="history-table"><thead><tr><th>ADVENTURER</th><th>FATE</th><th>FLOOR</th><th>SLAIN</th><th>GOLD</th><th>TIME</th></tr></thead><tbody>{progress.runs.map(run => <tr key={run.id}><td><span className="history-character">{characters.find(c => c.id === run.character)?.short}</span><small>{new Date(run.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</small></td><td><span className={run.outcome === 'fallen' ? 'fate-fallen' : 'fate-retreated'}>{run.outcome === 'fallen' ? 'FALLEN' : 'RETREATED'}</span></td><td>{String(run.floor).padStart(2, '0')}</td><td>{run.kills}</td><td>{run.gold}</td><td>{formatTime(run.seconds)}</td></tr>)}</tbody></table></div>}
    </div>}
    <p className="armory-footnote"><Icon name="lock" size={13} />{persistent ? 'Unlocks and run history are saved on this device. Even the forgotten leave something behind.' : 'Browser storage is unavailable. Your progress is kept for this session only.'}</p>
  </main>;
}