import { useState, type CSSProperties } from 'react';
import type { Character } from '../data';
import { abilitiesFor, abilityCostLabel } from '../game/abilities';
import { MAX_HERO_LEVEL, attributeCost, attributeRankCap, attributeEffects, attributeNames, heroStats, resourceFor, xpToNext, type Attribute, type HeroProgress } from '../progression';
import type { ShopAction, ShopResult } from '../economy';
import Icon from './Icon';

export default function HeroMastery({ hero, mastery, owned, onTransaction }: { hero: Character; mastery: HeroProgress; owned: boolean; onTransaction: (action: ShopAction) => ShopResult }) {
  const [selected, setSelected] = useState(0);
  const [message, setMessage] = useState('');
  const abilities = abilitiesFor(hero), resource = resourceFor(hero), stats = heroStats(hero, mastery);
  const ability = abilities[selected], capped = mastery.level === MAX_HERO_LEVEL, next = abilities.find(item => item.level > mastery.level);
  const transact = (action: ShopAction) => { const result = onTransaction(action); setMessage(result.message); };
  return <section className="hero-mastery" style={{ '--mastery-color': hero.color } as CSSProperties} aria-label={`${hero.name} mastery`}>
    <div className="mastery-topline"><div className="mastery-level"><span className="mastery-level-number">{String(mastery.level).padStart(2, '0')}</span><div><span className="micro-label">HERO MASTERY / MAX LEVEL 15</span><h3>{capped ? 'Every power. Fully awakened.' : next ? `Next awakening: ${next.name}` : 'Keep your story growing.'}</h3><p>{capped ? 'You have reached the level cap.' : `Level up by playing${next ? `. Next ability at level ${next.level}` : ''}. No gold or shards required.`}</p></div></div><span className="xp-only-label"><Icon name={capped ? 'check' : 'sword'} size={18} />{capped ? 'LEVEL 15 / MAX' : 'EARNED IN THE DUNGEON'}</span></div>
    <div className="mastery-xp" role="progressbar" aria-label="Hero level progress" aria-valuemin={0} aria-valuemax={capped ? 1 : xpToNext(mastery.level)} aria-valuenow={capped ? 1 : mastery.xp}><span style={{ width: `${capped ? 100 : mastery.xp / xpToNext(mastery.level) * 100}%` }} /></div><div className="mastery-xp-caption"><span>{capped ? 'LEVEL 15 / MAX' : `${mastery.xp} / ${xpToNext(mastery.level)} XP`}</span><span>PROGRESSION SAVED FOR THIS HERO</span></div>
    <div className="mastery-abilities" role="tablist" aria-label="Six hero abilities">{abilities.map((item, index) => <button key={item.id} id={`ability-tab-${item.id}`} role="tab" aria-selected={selected === index} aria-controls={`ability-detail-${hero.id}`} tabIndex={selected === index ? 0 : -1} onKeyDown={event => { if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') { event.preventDefault(); const next = (index + (event.key === 'ArrowRight' ? 1 : abilities.length - 1)) % abilities.length; setSelected(next); (event.currentTarget.parentElement?.children[next] as HTMLElement)?.focus(); } }} onClick={() => setSelected(index)} className={`${selected === index ? 'selected' : ''} ${mastery.level < item.level ? 'locked' : ''}`}><span className="ability-unlock-level">{item.level === 1 ? 'STARTER' : `LV. ${item.level}`}</span><span className="mastery-ability-icon"><Icon name={item.icon} size={23} />{mastery.level < item.level && <Icon className="ability-mini-lock" name="lock" size={10} />}</span><strong>{item.name}</strong><small>{mastery.level < item.level ? 'LOCKED' : index === 0 ? 'PRIMARY ATTACK' : index === 5 ? 'ULTIMATE READY' : 'UNLOCKED'}</small></button>)}</div>
    <div className={`mastery-ability-detail ${resource.kind === 'blood' ? 'blood-resource' : ''}`} id={`ability-detail-${hero.id}`} role="tabpanel" aria-labelledby={`ability-tab-${ability.id}`}><Icon name={ability.icon} size={25} /><div><h4>{ability.name}<span>{mastery.level < ability.level ? `UNLOCKS AT LEVEL ${ability.level}` : 'AVAILABLE'}</span></h4><p>{ability.description}</p><div className="ability-detail-meta"><span><Icon name={resource.kind === 'blood' ? 'heart' : 'bolt'} size={12} />{abilityCostLabel(hero, ability)}</span><span><Icon name="clock" size={12} />{ability.cooldown}s COOLDOWN</span>{selected === 5 && <span>LEVEL 15 ULTIMATE</span>}</div></div></div>
    <div className="hero-resource-note"><span style={{ color: resource.color }}><Icon name={resource.kind === 'blood' ? 'heart' : 'bolt'} size={17} />{resource.name}</span><p>{resource.description}</p><div><strong>{stats.hp.toLocaleString()}</strong> HP <i /> <strong>{stats.stamina}</strong> STA <i /> <strong>{stats.damage}</strong> DAMAGE</div></div>
    <div className="attribute-heading"><span className="micro-label">PERMANENT ATTRIBUTES</span><span><Icon name="gem" size={13} />{mastery.points} POINT{mastery.points !== 1 ? 'S' : ''} AVAILABLE</span></div>
    <div className="attribute-upgrades">{(Object.keys(attributeNames) as Attribute[]).map(attribute => <div key={attribute}><Icon name={attribute === 'vitality' ? 'heart' : attribute === 'endurance' ? 'bolt' : 'sword'} size={19} /><div><h4>{attributeNames[attribute]} <small>RANK {mastery.attributes[attribute]}</small></h4><p>{attributeEffects[attribute]} / {attributeCost(mastery.attributes[attribute])} point cost</p></div><button aria-label={`Upgrade ${attributeNames[attribute]}, costs ${attributeCost(mastery.attributes[attribute])} points`} disabled={!owned || mastery.points < attributeCost(mastery.attributes[attribute]) || mastery.attributes[attribute] >= attributeRankCap(mastery.level)} onClick={() => transact({ type: 'attribute', id: hero.id, attribute })}>+</button></div>)}</div>
    <div className="progression-explainer"><p><strong>How you earn XP:</strong> bosses, mini-bosses, ordinary enemies, floor completion, and mastery caches. Bosses and mini-bosses are the biggest rewards.</p><p><strong>Build, don\'t max everything:</strong> one attribute point at each even hero level, plus up to four rare bonus points per hero. Higher ranks cost more and require higher levels. Current rank cap: {attributeRankCap(mastery.level)}.</p></div>
    {message && <p className="mastery-message" role="status">{message}</p>}
    {!owned && <p className="mastery-locked-note"><Icon name="lock" size={12} />Recruit this hero to begin their journey. Every hero begins at level 1.</p>}
  </section>;
}