import { useState } from 'react';
import type { Character } from '../data';
import type { GameHUD } from '../game/engine';
import { runCharms, sealDefinitions, type CharmId } from '../game/rewards';
import { attributeCost, attributeRankCap, attributeEffects, attributeNames, resourceFor, type Attribute } from '../progression';
import { abilitiesFor, abilityCostLabel } from '../game/abilities';
import Icon from './Icon';
import Modal from './Modal';

export default function RunInventory({ hud, hero, onEquip, onAttribute, onClose }: { hud: GameHUD; hero: Character; onEquip: (id: string | null) => void; onAttribute: (attribute: Attribute) => void; onClose: () => void }) {
  const [tab, setTab] = useState<'seals' | 'mastery' | 'powers'>('seals');
  return <Modal label="Run inventory" className="run-inventory-modal" onClose={onClose}>
    <div className="modal-heading"><div><span className="eyebrow">THIS DESCENT. THIS LIFE.</span><h2>Your Run Inventory</h2></div><button className="icon-button" aria-label="Close run inventory and resume" onClick={onClose}><Icon name="close" /></button></div>
    <div className="panel-tabs" role="tablist" aria-label="Run inventory sections">{(['seals', 'mastery', 'powers'] as const).map(section => <button key={section} role="tab" aria-selected={tab === section} className={tab === section ? 'active' : ''} onClick={() => setTab(section)}><Icon name={section === 'seals' ? 'crown' : section === 'mastery' ? 'shield' : 'bolt'} size={16} />{section.toUpperCase()}{section === 'mastery' && hud.heroProgress.points > 0 && <span>{hud.heroProgress.points}</span>}</button>)}</div>
    <div className="run-inventory-body" role="tabpanel" aria-label={tab}>
      {tab === 'seals' && <><p className="run-only-warning"><Icon name="skull" size={16} />Seals and charms belong to this run. Death, retreat, or starting over destroys them.</p>{hud.seals.length ? <div className="seal-list">{hud.seals.map(seal => { const definition = sealDefinitions[seal.kind]; return <article key={seal.id} className={`seal-entry ${hud.equippedSeal === seal.id ? 'equipped' : ''}`}><div className="seal-art" style={{ color: definition.color }}><Icon name="crown" size={31} /></div><div><span className="micro-label">MYTHIC SEAL / TIER {seal.tier} / FLOOR {seal.floor}</span><h3 style={{ color: definition.color }}>{definition.name}</h3><strong>{definition.power}</strong><p>{definition.description}</p><small>{definition.cost} {resourceFor(hero).kind === 'blood' ? 'STAMINA' : resourceFor(hero).name.toUpperCase()} / {definition.cooldown}s cooldown</small></div><button className={hud.equippedSeal === seal.id ? 'outline-button small' : 'gold-button small'} onClick={() => onEquip(hud.equippedSeal === seal.id ? null : seal.id)}>{hud.equippedSeal === seal.id ? 'UNEQUIP' : 'EQUIP'}</button></article>; })}</div> : <div className="empty-seals"><Icon name="crown" size={38} /><h3>No borrowed power. Yet.</h3><p>Bosses always drop rare loot. Only a lucky few leave a seal.<br />Claim a dropped seal, equip it here, and wield the boss's ultimate.</p><span>6% BASE DROP CHANCE / UP TO 12% IN DEEPER FLOORS</span></div>}
        <div className="run-charms"><span className="micro-label">TEMPORARY CHARMS / AUTOMATICALLY ACTIVE</span>{Object.entries(hud.charms).length ? Object.entries(hud.charms).map(([id, count]) => <div key={id}><Icon name={id === 'fang' ? 'sword' : id === 'pearl' ? 'shield' : 'flame'} size={20} style={{ color: runCharms[id as CharmId].color }} /><div><h4>{runCharms[id as CharmId].name} <span>x{count}</span></h4><p>{runCharms[id as CharmId].description}</p></div></div>) : <p>No charms found. Rare chests and defeated guardians can contain them.</p>}</div></>}
      {tab === 'mastery' && <><div className="inventory-hero-level"><div><span className="micro-label">{hero.name.toUpperCase()}</span><h3>Level {hud.heroProgress.level} <small>/ 15</small></h3></div><span>{hud.xpNext ? `${hud.heroProgress.xp} / ${hud.xpNext} XP` : 'MAX LEVEL'}</span></div><p className="inventory-persistent-note">XP-only leveling. One point per even level and up to four rare bonus points per hero. {hud.heroProgress.points} point{hud.heroProgress.points !== 1 ? 's' : ''} available.</p><div className="inventory-attributes">{(Object.keys(attributeNames) as Attribute[]).map(attribute => <div key={attribute}><div><h3>{attributeNames[attribute]} <span>Rank {hud.heroProgress.attributes[attribute]} / Current cap {attributeRankCap(hud.heroProgress.level)}</span></h3><p>{attributeEffects[attribute]}</p></div><button className="outline-button small" disabled={hud.heroProgress.points < attributeCost(hud.heroProgress.attributes[attribute]) || hud.heroProgress.attributes[attribute] >= attributeRankCap(hud.heroProgress.level)} onClick={() => onAttribute(attribute)}>+ {attributeCost(hud.heroProgress.attributes[attribute])} POINTS</button></div>)}</div></>}
      {tab === 'powers' && <div className="inventory-powers">{abilitiesFor(hero).map(ability => <article key={ability.id} className={hud.heroProgress.level < ability.level ? 'locked' : ''}><Icon name={hud.heroProgress.level < ability.level ? 'lock' : ability.icon} size={23} /><div><h3>{ability.name}<span>LV. {ability.level}</span></h3><p>{ability.description}</p><small>{abilityCostLabel(hero, ability)} / {ability.cooldown}s COOLDOWN</small></div></article>)}</div>}
    </div>
    <div className="run-inventory-footer"><span><Icon name="pause" size={12} />GAME AND BOOST TIMERS PAUSED</span><button className="gold-button small" onClick={onClose}>BACK TO THE DEPTHS<Icon name="arrow" size={16} /></button></div>
  </Modal>;
}